### ISSUE TITLE
Render source

### ISSUE THREAD

**Issue by fornellas** [Cyboard-DigitalTailor/renders#1]
Hi,

I was wondering whether the source for the renders (such as https://github.com/Cyboard-DigitalTailor/renders/blob/main/dactyl-manuform/Dactyl_Letters-Numbers-Functions_Original-Thumb.stl) are publically available. I'd love to tweak the design, by adding some extra keys (I really miss having all arrow keys on the right side).

Thanks!

**Comment by RealET** [comment]
Hi @fornellas , The source for this model is not currently available, but you should be able to create the same model in this great generator: https://ryanis.cool/cosmos/.
